// ce poate vedea fiecare rol in sidebar si in aplicatie
export const ROLURI = {
  hr_specialist: {
    label:    'HR Specialist',
    culoare:  '#4ec9b0',
    poate: {
      angajati:       true,
      salarii:        false,
      cnp:            false,
      concedii:       true,
      evaluari:       false,
      beneficii:      true,
      proiecte:       false,
      departamente:   true,
      pozitii:        true,
      ml:             false,
      rapoarte:       false,
      audit:          false,
      view_hr:        true,
    }
  },
  hr_manager: {
    label:    'HR Manager',
    culoare:  '#ff22a1',
    poate: {
      angajati:       true,
      salarii:        true,
      cnp:            true,
      concedii:       true,
      evaluari:       true,
      beneficii:      true,
      proiecte:       false,
      departamente:   true,
      pozitii:        true,
      ml:             true,
      rapoarte:       true,
      audit:          true,
      view_hr:        true,
      view_subordonati: true,
    }
  },
  team_leader: {
    label:    'Team Leader',
    culoare:  '#f39c12',
    poate: {
      angajati:       false,
      salarii:        false,
      cnp:            false,
      concedii:       true,
      evaluari:       true,
      beneficii:      false,
      proiecte:       false,
      departamente:   false,
      pozitii:        false,
      ml:             false,
      rapoarte:       false,
      audit:          false,
      view_hr:        false,
      view_echipa:    true,
      view_subordonati: true,
    }
  },
  project_manager: {
    label:    'Project Manager',
    culoare:  '#9b59b6',
    poate: {
      angajati:       false,
      salarii:        false,
      cnp:            false,
      concedii:       false,
      evaluari:       false,
      beneficii:      false,
      proiecte:       true,
      departamente:   false,
      pozitii:        false,
      ml:             false,
      rapoarte:       false,
      audit:          false,
      view_proiecte:  true,
    }
  },
  director: {
    label:    'Director',
    culoare:  '#3498db',
    poate: {
      angajati:       true,
      salarii:        true,
      cnp:            false,
      concedii:       true,
      evaluari:       true,
      beneficii:      true,
      proiecte:       true,
      departamente:   true,
      pozitii:        true,
      ml:             true,
      rapoarte:       true,
      audit:          false,
      readonly:       true,
      view_subordonati: true,
    }
  },
  ceo: {
    label:    'CEO',
    culoare:  '#e74c3c',
    poate: {
      angajati:       true,
      salarii:        true,
      cnp:            true,
      concedii:       true,
      evaluari:       true,
      beneficii:      true,
      proiecte:       true,
      departamente:   true,
      pozitii:        true,
      ml:             true,
      rapoarte:       true,
      audit:          true,
      readonly:       true,
      view_subordonati: true,
    }
  },
  app_readonly: {
    label:    'Read Only',
    culoare:  '#808080',
    poate: {
      angajati:       true,
      salarii:        false,
      cnp:            false,
      concedii:       false,
      evaluari:       false,
      beneficii:      true,
      proiecte:       true,
      departamente:   true,
      pozitii:        true,
      ml:             false,
      rapoarte:       false,
      audit:          false,
      readonly:       true,
    }
  },
};

export const getRolPermisiuni = (rol) => ROLURI[rol] || ROLURI['app_readonly'];
export const poateFace = (rol, actiune) => getRolPermisiuni(rol)?.poate[actiune] || false;
